# base image source https://github.com/rhdt/EL-Dockerfiles/blob/master/base/jboss-jdk-8/Dockerfile

FROM prod.registry.devshift.net/osio-prod/base/jboss-jdk-8:latest

EXPOSE 8182

ENV M2_DIR=/m2
ENV M2_REPO=${M2_DIR}/repository
ENV MAVEN_OPTS="-Dmaven.repo.local=${M2_REPO}"

RUN git clone https://github.com/awslabs/dynamodb-janusgraph-storage-backend.git /opt/dynamodb/dynamodb-janusgraph-storage-backend/ &&\
    cd /opt/dynamodb-janusgraph-storage-backend &&\
    mvn clean install

RUN cd /opt/dynamodb/dynamodb-janusgraph-storage-backend/ &&\
    sed -i "\#gpg --verify src/test/resources/${JANUSGRAPH_VANILLA_SERVER_ZIP}#d" src/test/resources/install-gremlin-server.sh &&\
    sed -i 's#JANUSGRAPH_VANILLA_SERVER_ZIP=.*#JANUSGRAPH_VANILLA_SERVER_ZIP=/opt/dynamodb/dynamodb-janusgraph-storage-backend/server/janusgraph-0.2.0-hadoop2.zip#' src/test/resources/install-gremlin-server.sh &&\
    src/test/resources/install-gremlin-server.sh

WORKDIR /opt/dynamodb/

# Install Gremlin Python
RUN mkdir -p ${M2_REPO}/repository/org/slf4j/slf4j-api/1.7.21/ &&\
rm -rf ~/.m2/repository &&\
    rm -rf ~/.groovy/grapes &&\
    cd dynamodb-janusgraph-storage-backend/server/dynamodb-janusgraph-storage-backend-1.2.0 &&\
    curl -o ${M2_REPO}/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar http://central.maven.org/maven2/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar &&\
    bin/gremlin-server.sh -i org.apache.tinkerpop gremlin-python 3.2.3

ADD scripts/entrypoint.sh /bin/entrypoint.sh

RUN chmod +x /bin/entrypoint.sh &&\
    chgrp -R 0 /opt/dynamodb/ &&\
    chmod -R g+rw /opt/dynamodb/ &&\
    find /opt/dynamodb/ -type d -exec chmod g+x {} +

ADD scripts/entrypoint-local.sh /bin/entrypoint-local.sh
RUN chmod +x /bin/entrypoint-local.sh

COPY scripts/post-hook.sh /bin/

# We have already built everything, so remove the local repo now
#RUN rm -rf /opt/titan-1.1.0-SNAPSHOT-hadoop2.zip /opt/dynamodb/dynamodb-titan-storage-backend/server/dynamodb-titan100-storage-backend-1.0.0-hadoop1.zip

ENTRYPOINT ["/bin/entrypoint.sh"]
